# PostgreSQL for local runs
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55433/restaurant}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
