spring.application.name=restaurant

spring.profiles.default=local

spring.jackson.property-naming-strategy=SNAKE_CASE

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.docker.compose.enabled=false
