CREATE TABLE order_ratings (
    order_rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_rating_score INTEGER NOT NULL CHECK (order_rating_score BETWEEN 1 AND 5),
    order_rating_comment VARCHAR(1000),
    order_rating_created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_order_ratings_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_order_ratings_order UNIQUE (order_id)
);
