ALTER TABLE orders
    ADD COLUMN address_id BIGINT,
    ADD COLUMN customer_note VARCHAR(255);

INSERT INTO addresses (
    customer_id,
    address_label,
    address_line,
    address_city,
    address_area,
    address_note,
    address_is_default,
    address_created_at
)
SELECT DISTINCT
    orders.customer_id,
    'Legacy address',
    'Unknown',
    'Unknown',
    'Unknown',
    'Backfilled for existing orders',
    FALSE,
    CURRENT_TIMESTAMP
FROM orders
WHERE NOT EXISTS (
    SELECT 1
    FROM addresses
    WHERE addresses.customer_id = orders.customer_id
);

UPDATE orders
SET address_id = address_choice.address_id
FROM (
    SELECT DISTINCT ON (customer_id)
        customer_id,
        address_id
    FROM addresses
    ORDER BY customer_id, address_is_default DESC, address_created_at DESC, address_id DESC
) AS address_choice
WHERE orders.customer_id = address_choice.customer_id
  AND orders.address_id IS NULL;

ALTER TABLE orders
    ALTER COLUMN address_id SET NOT NULL,
    ADD CONSTRAINT fk_orders_address
        FOREIGN KEY (address_id)
        REFERENCES addresses (address_id);

CREATE TABLE transaction (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_provider_code BIGINT,
    transaction_number BIGINT,
    order_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL,
    transaction_amount NUMERIC(19, 2),
    transaction_date TIMESTAMP,
    CONSTRAINT fk_transaction_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON DELETE CASCADE
);

CREATE TABLE order_tracking (
    order_tracking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_status VARCHAR(255) NOT NULL,
    order_tracking_date TIMESTAMP NOT NULL,
    restaurant_id BIGINT NOT NULL,
    CONSTRAINT fk_order_tracking_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_order_tracking_order_id ON order_tracking (order_id);
