-- Display metadata for a saved card, nothing more. There is no payment
-- gateway: the full card number (PAN) and CVV are never accepted or stored,
-- which keeps the project out of PCI-DSS scope.
CREATE TABLE payment_methods (
    payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    payment_method_brand VARCHAR(20) NOT NULL,
    payment_method_last4 CHAR(4) NOT NULL,
    payment_method_expiry_month SMALLINT NOT NULL,
    payment_method_expiry_year SMALLINT NOT NULL,
    payment_method_holder_name VARCHAR(150) NOT NULL,
    payment_method_is_default BOOLEAN NOT NULL DEFAULT FALSE,
    payment_method_created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_methods_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_payment_methods_expiry_month
        CHECK (payment_method_expiry_month BETWEEN 1 AND 12)
);

CREATE INDEX idx_payment_methods_customer_id ON payment_methods (customer_id);

-- At most one default per customer, as V8 does for addresses.
CREATE UNIQUE INDEX uq_payment_methods_one_default_per_customer
    ON payment_methods (customer_id)
    WHERE payment_method_is_default;
