CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150) NOT NULL,
    user_email VARCHAR(255) NOT NULL UNIQUE,
    user_password VARCHAR(255) NOT NULL
);

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_customers_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE TABLE restaurants (
    restaurant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    restaurant_name VARCHAR(255) NOT NULL,
    restaurant_description TEXT,
    CONSTRAINT fk_restaurants_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE TABLE menus (
    menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    menu_code VARCHAR(100) NOT NULL UNIQUE,
    menu_category VARCHAR(100) NOT NULL,
    CONSTRAINT fk_menus_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants (restaurant_id)
        ON DELETE CASCADE
);

CREATE TABLE menu_items (
    menu_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    menu_item_code VARCHAR(100) NOT NULL UNIQUE,
    menu_item_image_url TEXT,
    menu_item_price NUMERIC(12, 2) NOT NULL CHECK (menu_item_price >= 0),
    CONSTRAINT fk_menu_items_menu
        FOREIGN KEY (menu_id)
        REFERENCES menus (menu_id)
        ON DELETE CASCADE
);

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_carts_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE CASCADE
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    cart_item_quantity INTEGER NOT NULL CHECK (cart_item_quantity > 0),
    cart_item_price NUMERIC(12, 2) NOT NULL CHECK (cart_item_price >= 0),
    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts (cart_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_menu_item
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items (menu_item_id),
    CONSTRAINT uq_cart_items_cart_menu_item
        UNIQUE (cart_id, menu_item_id)
);

CREATE INDEX idx_customers_user_id ON customers (user_id);
CREATE INDEX idx_restaurants_user_id ON restaurants (user_id);
CREATE INDEX idx_menus_restaurant_id ON menus (restaurant_id);
CREATE INDEX idx_menu_items_menu_id ON menu_items (menu_id);
CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX idx_cart_items_menu_item_id ON cart_items (menu_item_id);
