-- Step 2 of the use-case: restaurant open/closed. A flag, not opening hours.
ALTER TABLE restaurants
    ADD COLUMN restaurant_is_open BOOLEAN NOT NULL DEFAULT TRUE;

-- menu_items has menu_item_code and menu_item_note, but no readable name.
-- CartItemMapper currently puts the code into the response's itemName.
ALTER TABLE menu_items
    ADD COLUMN menu_item_name VARCHAR(150);

UPDATE menu_items SET menu_item_name = 'Kofta Platter'    WHERE menu_item_code = 'NK-KOFTA-01';
UPDATE menu_items SET menu_item_name = 'Falafel Sandwich' WHERE menu_item_code = 'NK-FALAFEL-01';
UPDATE menu_items SET menu_item_name = 'Koshari Bowl'     WHERE menu_item_code = 'NK-KOSHARI-01';
UPDATE menu_items SET menu_item_name = 'Classic Burger'   WHERE menu_item_code = 'BY-CLASSIC-01';
UPDATE menu_items SET menu_item_name = 'Chicken Burger'   WHERE menu_item_code = 'BY-CHICKEN-01';
UPDATE menu_items SET menu_item_name = 'Fries'            WHERE menu_item_code = 'BY-FRIES-01';

-- No such rows exist today; this only makes the NOT NULL below safe.
UPDATE menu_items SET menu_item_name = menu_item_code WHERE menu_item_name IS NULL;

ALTER TABLE menu_items
    ALTER COLUMN menu_item_name SET NOT NULL;

-- A customer with no cart. V3 gave both existing customers one, leaving nothing
-- to exercise "create a cart when the customer has none".
INSERT INTO users (user_id, user_name, user_email, user_password) VALUES
    (5, 'Sara Nabil', 'sara.nabil@example.com', '$2a$10$placeholder.customer3');

INSERT INTO customers (customer_id, user_id) VALUES
    (3, 5);

-- A closed restaurant, so the open/closed rejection has a fixture. Both seeded
-- restaurants are open, leaving nothing to exercise it.
INSERT INTO users (user_id, user_name, user_email, user_password) VALUES
    (6, 'Late Night Grill', 'contact@latenight.example.com', '$2a$10$placeholder.restaurant3');

INSERT INTO restaurants (restaurant_id, user_id, restaurant_name, restaurant_description, restaurant_is_open) VALUES
    (3, 6, 'Late Night Grill', 'Closed for renovation.', FALSE);

INSERT INTO menus (menu_id, restaurant_id, menu_code, menu_category) VALUES
    (3, 3, 'LN-MAIN', 'Main');

INSERT INTO menu_items (menu_item_id, menu_id, menu_item_code, menu_item_name, menu_item_price, menu_item_stock) VALUES
    (7, 3, 'LN-WINGS-01', 'Buffalo Wings', 95.00, 30);

-- V2 and V3 inserted explicit ids into GENERATED BY DEFAULT AS IDENTITY columns,
-- which does not advance the identity. Without this the first row the
-- application inserts reuses id 1 and violates the primary key.
-- ALTER ... RESTART WITH is understood by both PostgreSQL and H2, unlike
-- setval(pg_get_serial_sequence(...)). The literals are one past the highest
-- seeded id in each table.
ALTER TABLE users       ALTER COLUMN user_id      RESTART WITH 7;
ALTER TABLE customers   ALTER COLUMN customer_id  RESTART WITH 4;
ALTER TABLE restaurants ALTER COLUMN restaurant_id RESTART WITH 4;
ALTER TABLE menus       ALTER COLUMN menu_id      RESTART WITH 4;
ALTER TABLE menu_items  ALTER COLUMN menu_item_id RESTART WITH 8;
ALTER TABLE carts       ALTER COLUMN cart_id      RESTART WITH 3;
ALTER TABLE cart_items  ALTER COLUMN cart_item_id RESTART WITH 4;
