CREATE TABLE addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    address_label VARCHAR(100) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    address_city VARCHAR(100) NOT NULL,
    address_area VARCHAR(100) NOT NULL,
    address_note TEXT,
    address_is_default BOOLEAN NOT NULL DEFAULT FALSE,
    address_created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_addresses_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_addresses_customer_id ON addresses (customer_id);
