-- The order epic's foundation. #47 lands before anything writes a status, so
-- it carries the tables that status lives on. #35 fills them at checkout.
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    -- Who may accept or reject. Denormalised from the lines; safe only because
    -- a cart holds items from a single restaurant. If multi-restaurant carts
    -- are ever allowed this breaks, which is the intended tripwire.
    restaurant_id BIGINT NOT NULL,
    -- Plain varchar with no CHECK: a deliberate least-resistance choice. The
    -- vocabulary is enforced in Java only. See the use-case spec.
    order_status VARCHAR(32) NOT NULL,
    order_total NUMERIC(12, 2) NOT NULL CHECK (order_total >= 0),
    order_created_at TIMESTAMPTZ NOT NULL,
    -- Captured on accept (#48). Nullable and unconsumed: it is what makes an
    -- ETA possible later, and adding it now avoids a migration plus a backfill
    -- of nulls across every existing order.
    order_prep_time_minutes INTEGER CHECK (order_prep_time_minutes > 0),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (customer_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants (restaurant_id)
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    -- Snapshots. A menu item can be renamed or repriced; an order must not change.
    order_item_name VARCHAR(150) NOT NULL,
    order_item_quantity INTEGER NOT NULL CHECK (order_item_quantity > 0),
    order_item_price NUMERIC(12, 2) NOT NULL CHECK (order_item_price >= 0),
    order_item_note VARCHAR(255),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_menu_item
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items (menu_item_id)
);

-- One row per transition. #34 chose this over moving rows between tables: a
-- separate order_history table is migration risk for no gain, and every read
-- of a delivered order would become a join.
CREATE TABLE order_status_history (
    order_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_status_history_from VARCHAR(32) NOT NULL,
    order_status_history_to VARCHAR(32) NOT NULL,
    -- Includes SYSTEM, for the 15-minute auto-reject in #48.
    order_status_history_actor_role VARCHAR(32) NOT NULL,
    order_status_history_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_order_status_history_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON DELETE CASCADE
);

-- The keyset access path for order history (GH-37): filter on customer, sort
-- on the composite cursor. Without it both history queries seq-scan.
CREATE INDEX idx_orders_customer_created
    ON orders (customer_id, order_created_at DESC, order_id DESC);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_status_history_order_id ON order_status_history (order_id);
